spring:
  datasource:
    url: jdbc:postgresql://postgres-1.cgkybqnrfkrn.eu-north-1.rds.amazonaws.com:5432/tms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect