name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image for api
      run: docker build -t api ./api
    - name: Build the Docker image for api
      run: docker tag api:latest alciel/api:latest    
    - name: Push to Dockerhub
      run: docker push alciel/api:latest
      
    - name: Build the Docker image for front
      run: docker build -t front ./front
    - name: Build the Docker image for front
      run: docker tag front:latest alciel/front:latest    
    - name: Push to Dockerhub
      run: docker push alciel/front:latest
